#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo /Users/me/.local/bin/yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# yabai -m config external_bar               all:0:0
yabai -m config window_border              on
yabai -m config mouse_follows_focus        off
yabai -m config focus_follows_mouse        off
yabai -m config window_placement           second_child
yabai -m config window_topmost             off
yabai -m config window_shadow              on
yabai -m config window_opacity             on
# yabai -m config window_opacity_duration    0.0
yabai -m config active_window_opacity      1.0
yabai -m config normal_window_opacity      0.75
yabai -m config window_border_width        6
yabai -m config active_window_border_color 0xff52bdff
yabai -m config normal_window_border_color 0xff161616
yabai -m config insert_feedback_color      0x6633b1ff
yabai -m config split_ratio                0.62
yabai -m config auto_balance               off
yabai -m config mouse_modifier             fn
yabai -m config mouse_action1              move
yabai -m config mouse_action2              resize
yabai -m config mouse_drop_action          swap


yabai -m config layout                     bsp
yabai -m config top_padding                23
yabai -m config bottom_padding             20
yabai -m config left_padding               20
yabai -m config right_padding              20
yabai -m config window_gap                 20
# Do not manage some apps which are not resizable
yabai -m rule --add app="^(mpv|qemu-system-aarch64|Simulator|Android Studio|JetBrains|LuLu|Vimac|Calculator|Spotify|GoLand|Webstorm|CLion|VLC|System Preferences|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice)$" manage=off

# ===== Rules ==================================

yabai -m rule --add label="Steam" app="^Steam$" space=5 manage=off
yabai -m rule --add label="Outlook" app="^Microsoft .*$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="PopUp" app="^kitty$" title="^PopUp$" manage=off border=off grid=7:5:3:4:2:3
yabai -m rule --add label="Mail" app="^kitty$" title="^Mail$" manage=off border=on grid=7:5:1:4:3:4
yabai -m rule --add label="Launcher" app="^kitty$" title="^Launcher$" manage=off border=off grid=9:9:3:2:3:2
yabai -m rule --add label="Alfred" app="^Alfred$" manage=off
yabai -m rule --add label="Firefox" app="Firefox$" title="^(Library|History|General|(Download|Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="Software Update" title="^Software Update" manage=off
yabai -m rule --add label="About This Mac" app="^System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m space 1 --label gen
yabai -m space 2 --label browser 
yabai -m space 3 --label ide
yabai -m space 4 --label tools
yabai -m space 5 --label spotify

echo "yabai configuration loaded.."
