#!/bin/bash


alias \
  padd='sudo port install -c' \
  pset='sudo port select --set' \
  psel='sudo port select --summary' \
  pinfo='sudo port info' \
  psearch='sudo port search' \
  pvars='sudo port variants' \
  prm='sudo port uninstall -Ruc'

