#!/usr/bin/env bash

dark_mode ()
{
  # night_time=('6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '20')
  # day_time=('21' '22' '23' '0' '1' '2' '3' '4' '5')

  day_time=('6' '7' '8' '9' '10' '11' '12' '13' '14' '15' '16' '17' '18' '19' '20')
  night_time=('21' '22' '23' '0' '1' '2' '3' '4' '5')


  for hour in "${day_time[@]}"; do
    if [[ $(date '+%H') = "$hour" ]]; then
      python3 /Users/me/.local/bin/scripts/darkmode.py 'day'
      return
    fi
  done
  for night_hour in "${night_time[@]}"; do
    if [[ $(date '+%H') = "$night_hour" ]]; then
      python3 /Users/me/.local/bin/scripts/darkmode.py 'night'
      return
    fi
  done
}
